
policy:
  approval:
    - the fintoc team has approved


approval_rules:
  - name: the fintoc team has approved
    options:
      request_review:
        enabled: true
        mode: random-users
    requires:
      count: 2
      teams: ["fintoc-com/core-team"]
