
policy:
  approval:
    - someone from fintoc has approved
    - the dashboard team has approved
    - a fintoc front maintainer has approved


approval_rules:
  - name: someone from fintoc has approved
    options:
      request_review:
        enabled: true
        mode: random-users
    requires:
      count: 1
      teams: ["fintoc-com/core-team"]
  - name: the dashboard team has approved
    options:
      request_review:
        enabled: true
        mode: random-users
    requires:
      count: 1
      teams: ["paulamardones", "daleal", "parayab"]
  - name: a fintoc front maintainer has approved
    if:
      has_not_labels:
        - "tank"
    options:
      request_review:
        enabled: true
        mode: random-users
    requires:
      count: 1
      users: ["nateare"]
