export const WEBHOOK_EXAMPLE = {
  id: 'evt_wVq5KXC1qDQRZkPr',
  type: 'link.credentials_changed',
  mode: 'test',
  created_at: '2022-04-05T01:25:31.911Z',
  data: {
    id: 'link_00000000',
    holder_id: '415792638',
    username: '415792638',
    holder_type: 'individual',
    created_at: null,
    institution: {
      id: 'cl_banco_falabella',
      name: 'Banco Falabella',
      country: 'cl',
    },
    link_token: null,
    mode: 'test',
    active: true,
    status: 'active',
    object: 'link',
    accounts: null,
  },
  object: 'event',
};
