version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout

      - run:
          name: Install Doppler CLI
          command: (curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sudo sh


      - restore_cache:
          keys:
          - yarn-dependencies-{{ checksum "yarn.lock" }}
          - yarn-dependencies-

      - run:
          name: Install yarn dependencies
          command: yarn install

      - save_cache:
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Start Test Server
          command: doppler run -- yarn serve --port=4444
          background: true

      - run:
          shell: /bin/sh
          command: |
            wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:4444
            :

      - run:
          name: Run jest tests
          command: doppler run -- yarn test --runInBand

  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-dependencies-{{ checksum "yarn.lock" }}
          - yarn-dependencies-

      - run:
          name: Install yarn dependencies
          command: yarn install

      - save_cache:
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Install reviewdog
          command: |
            curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ./bin

      - run:
          name: Get files to lint
          command: mkdir tmp && git diff origin/master --name-only --diff-filter=d > tmp/files_to_lint

      - run:
          name: Run eslint
          shell: /bin/bash
          command: |
            cat tmp/files_to_lint | grep -E '.+\.(js|jsx|vue)$' | xargs yarn run eslint \
            | ./bin/reviewdog -reporter=github-pr-review -f=eslint

workflows:
  version: 2
  test_and_lint:
    jobs:
      - lint:
          context: org-global
      - test:
          context: org-global
