const PRODUCTDESCRIPTION = {
  MOVEMENTS: 'Accede a los movimientos bancarios históricos de tus usuarios. Los datos transaccionales pueden ser útiles para una cantidad infinita de aplicaciones, como la gestión de finanzas personales, informes de gastos, conciliación bancaria, flujo de efectivo, análisis de riesgo y más.',
  SUBSCRIPTION: 'Genera pagos recurrentes con el banco. Las suscripciones permiten que tus usuarios puedan realizar pagos recurrentes dentro de tu aplicación.',
  PAYMENTS: 'Permite a tus usuarios transferir o cobrar dinero entre cuentas bancarias chilenas desde tu aplicación.',
  REFRESH_INTENT: 'Genera actualizaciones on-demand de Links que ya están conectados a Fintoc y ve sus resultados. Recuerda que no es necesario utilizar recursos para consultar la API de Fintoc constantemente. A través de nuestro sistema de webhook, podemos avisar cada vez que se actualice una cuenta con los últimos movimientos disponibles en el banco.',
  TAX_RETURNS: 'Verifica rápidamente los ingresos y las capacidades financieras de tus usuarios. En Chile, el formulario de declaración anual de impuestos corresponde al formulario F22.',
  TAX_STATEMENTS: 'Accede a las declaraciones de impuestos mensuales y obtén detalles específicos sobre el historial de ingresos y las capacidades financieras de tus usuarios. En Chile, el formulario de declaración mensual de impuestos corresponde al formulario F29.',
  // INCOME: 'Receive Sii income documents like Boleta de Honorarios.',
  INVOICES: 'Accede a los registros de compra y venta de tus usuarios.',
};
const PRODUCTRESPONSEJSON = {
  MOVEMENTS: '{\n    "id": "mov_BO381oEATXonG6bj",\n    "object": "movement",\n    "amount": 59400,\n    "post_date": "2020-04-17T00:00:00.000Z",\n    "description": "Traspaso de:Fintoc SpA",\n    "transaction_date": "2020-04-16T11:31:12.000Z",\n    "currency": "CLP",\n    "reference_id": "123740123",\n    "type": "transfer",\n    "pending": false,\n    "recipient_account": null,\n    "sender_account": {\n        "holder_id": "771806538",\n        "holder_name": "Comercial y Producción SpA",\n        "number": "1530108000",\n        "institution": {\n          "id": "cl_banco_de_chile",\n          "name": "Banco de Chile",\n          "country": "cl"\n        }\n    },\n    "comment": "Pago factura 198"\n}',
  SUBSCRIPTION: '{\n    "id": "sub_n3WxkLAoC3k1l0wO",\n    "object": "subscription",\n    "amount_limit": null,\n    "customer_id": "111111111",\n    "account_id": "acc_3g9Lo1MTWKxoOP8r",\n    "created_at": "2021-07-09T01:42:41.197Z",\n    "active": true\n}',
  PAYMENTS: '{\n  "id": "pi_BO381oEATXonG6bj",\n  "object": "payment_intent",\n  "amount": 1000,\n  "currency": "CLP",\n  "widget_token": "pi_BO381oEATXonG6bj_sec_a4xK32BanKWYn",\n  "status": "created",\n  "reference_id": "90123712",\n  "transaction_date": "2021-10-15T15:24:15.474Z",\n  "mode": "live",\n  "recipient_account": {\n    "holder_id": "183917137",\n    "number": "123456",\n    "type": "checking_account",\n    "institution_id": "cl_banco_de_chile"\n  },\n  "sender_account": {\n    "holder_id": "192769065",\n    "number": "123456",\n    "type": "checking_account",\n    "institution_id": "cl_banco_estado"\n  },\n  "created_at": "2021-10-15T15:23:11.474Z",\n}',
  REFRESH_INTENT: '{\n    "id": "mov_BO381oEATXonG6bj",\n    "object": "movement",\n    "amount": 59400,\n    "post_date": "2020-04-17T00:00:00.000Z",\n    "description": "Traspaso de:Fintoc SpA",\n    "transaction_date": "2020-04-16T11:31:12.000Z",\n    "currency": "CLP",\n    "reference_id": "123740123",\n    "type": "transfer",\n    "pending": false,\n    "recipient_account": null,\n    "sender_account": {\n        "holder_id": "771806538",\n        "holder_name": "Comercial y Producción SpA",\n        "number": "1530108000",\n        "institution": {\n          "id": "cl_banco_de_chile",\n          "name": "Banco de Chile",\n          "country": "cl"\n        }\n    },\n    "comment": "Pago factura 198"\n}',
  TAX_RETURNS: '"{\n  "id": "taxret_nMNejK7BT8oGbvO4",\n  "object": "tax_return",\n  "institution_id": "cl_fiscal_sii",\n  "interval_unit": "annual",\n  "period": "2021",\n  "fiscal_year": "2021",\n  "currency": "CLP",\n  "document_number": "12345",\n  "taxpayer": {\n    "id": "777777777",\n    "name": "Fintoc SpA",\n    "institution_tax_payer": {\n      "phone": "999999999",\n      "email": "hello@fintoc.com",\n      "addresses": [\n        {\n          "city": "Santiago",\n          "code": "84345463",\n          "type": "DOMICILIO",\n          "number": "2461",\n          "region": "REGION METROPOLITANA",\n          "street": "LOS CONQUISTADORES",\n          "commune": "PROVIDENCIA",\n          "apartment": null\n        }\n      ],\n      "activities": [\n        {\n          "iva": false,\n          "code": "0123",\n          "category": "1",\n          "started_at": "2020-04-16T04:00:00.000Z",\n          "description": "Servicios de tecnología"\n        }\n      ],\n      "authorized_documents": [\n        {\n          "code": "33",\n          "description": "FACTURA ELECTRONICA",\n          "authorized_at": "2021-11-30T15:57:38.584Z",\n          "max_documents": 414\n        }\n      ]\n    }\n  },\n    "institution_tax_return": {\n    "refund_account": {\n      "holder_id": "117056856",\n      "holder_name": "Erlich Bachman",\n      "number": "123123123",\n      "institution": {\n        "id": "cl_banco_de_chile",\n        "name": "Banco de Chile",\n        "country": "cl"\n      }\n    },\n    "refund_amount": 1000,\n    "due_amount": 0,\n    "income": {\n      "fees_with_retention": 234212,\n      "withheld_fees": 42341,\n      "fees_without_retention": 512334,\n      "fees": 13123,\n      "salary": 2313123,\n    },\n  }\n}"',
  TAX_STATEMENTS: '"{\n  "id": "taxstmt_000000000",\n  "fiscal_year": 2021,\n  "document_number": "123456",\n  "period": "10",\n  "status": "Vigente",\n  "object": "tax_statement",\n  "currency": "CLP",\n  "institution_id": "cl_fiscal_sii",\n  "interval_unit": "monthly",\n  "institution_tax_statement": {\n    "total_payment": 2646845,\n    "total_debit": 1173692,\n    "total_credit": 403497,\n    "retention_fee": 6497,\n    "salary_tax": 1870153,\n    "monthly_provisional_payments": null\n    },\n  "taxpayer": {\n    "id": "777777777",\n    "name": "Fintoc SpA",\n    "institution_tax_payer": {\n      "phone": "999999999",\n      "email": "hello@fintoc.com",\n      "addresses": [\n        {\n          "city": "Santiago",\n          "code": "84345463",\n          "type": "DOMICILIO",\n          "number": "2461",\n          "region": "REGION METROPOLITANA",\n          "street": "LOS CONQUISTADORES",\n          "commune": "PROVIDENCIA",\n          "apartment": null\n        }\n      ],\n      "activities": [\n        {\n          "iva": false,\n          "code": "0123",\n          "category": "1",\n          "started_at": "2020-04-16T04:00:00.000Z",\n          "description": "Servicios de tecnología"\n        }\n      ],\n      "authorized_documents": [\n        {\n          "code": "33",\n          "description": "FACTURA ELECTRONICA",\n          "authorized_at": "2021-11-30T15:57:38.584Z",\n          "max_documents": 414\n        }\n      ]\n    }\n  }\n}"',
  INVOICES: '"{\n    "id": "inv_nMNejK7BT8oGbvO4",\n    "object": "invoice",\n    "number": "135",\n    "institution_id": "cl_fiscal_sii",\n    "issuer": {\n        "id": "117056856",\n        "name": "Hooli SpA",\n        "institution_tax_payer": null\n    },\n    "receiver": null,\n    "issue_type": "received",\n    "date": "2021-06-25T04:00:00.000Z",\n    "total_amount": 12123,\n    "net_amount": 12000,\n    "currency": "CLP",\n    "tax_period": "06/2021",\n    "institution_invoice": {\n        "received_at": "2021-06-25T19:27:04.000Z",\n        "accepted_at": null,\n        "confirmation_status": null,\n        "exempt_amount": 0,\n        "document_type": 34,\n        "total_documents": null,\n        "vat_amount": 123,\n        "fixed_assets_net_amount": null,\n        "fixed_assets_vat_amount": null,\n        "non_refundable_vat_amount": null,\n        "non_refundable_vat_code": null,\n        "non_credit_tax_amount": null,\n        "total_vat_withheld": 0,\n        "partial_vat_withheld": 0,\n        "non_withheld_vat": 0,\n        "own_vat": 0,\n        "third_party_vat": 0,\n        "common_use_vat": null,\n        "out_of_time_vat": 0,\n        "reference_type_code": null,\n        "reference_number": null,\n        "construction_company_credit": 0,\n        "free_zone_tax": 0,\n        "container_deposit_guarantee": 0,\n        "domestic_ticket_sales": 0,\n        "international_ticket_sales": 0,\n        "receipt_reference_number": null,\n        "settlement_issuer_id": null,\n        "vat_commisions": null,\n        "net_commissions": 0,\n        "exempt_commissions": 0,\n        "has_note": false,\n        "is_services_invoice": false,\n        "services_invoice": null,\n        "transaction_category": "Del Giro",\n        "invoice_status": \'registered\',\n        "other_taxes": {\n            "total_amount": 400,\n            "other_taxes_detail": [\n                {\n                    "tax_code": 14,\n                    "tax_rate": "19",\n                    "tax_amount": 400\n                }\n            ]\n        },\n        "tobacco_taxes": {\n            "cigars": 0,\n            "cigarettes": 0,\n            "processed_tobacco": 0\n        }\n    }\n}"',
};
const MOREINFOURL = {
  MOVEMENTS: 'https://docs.fintoc.com/docs/movements-walkthrough',
  SUBSCRIPTION: 'https://docs.fintoc.com/docs/subscriptions-walkthrough',
  PAYMENTS: 'https://docs.fintoc.com/docs/payment-intents-walkthrough',
  REFRESH_INTENT: 'https://docs.fintoc.com/reference/refresh-intents',
  TAX_RETURNS: 'https://docs.fintoc.com/docs/tax-returns-walkthrough',
  TAX_STATEMENTS: 'https://docs.fintoc.com/docs/tax-statements-walkthrough',
  INVOICES: 'https://docs.fintoc.com/docs/invoices-walkthrough',
};

export default {
  PRODUCTDESCRIPTION,
  PRODUCTRESPONSEJSON,
  MOREINFOURL,
};
